# Generated by Django 5.2.2 on 2026-03-14 15:04

import apps.users.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=50)),
                ('avatar_emoji', models.CharField(max_length=8)),
                ('created_at', models.BigIntegerField(default=apps.users.models.now_ms)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
