# Generated by Django 5.2.2 on 2026-03-19 02:06

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=apps.users.models.default_user_id, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
