# Generated by Django 5.2.2 on 2026-03-19 02:03

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listmember',
            name='joined_at',
            field=models.BigIntegerField(default=apps.users.models.now_ms),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='created_at',
            field=models.BigIntegerField(default=apps.users.models.now_ms),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='updated_at',
            field=models.BigIntegerField(default=apps.users.models.now_ms),
        ),
    ]
