# Generated by Django 5.2.2 on 2026-03-19 02:06

import apps.lists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_alter_listmember_joined_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='id',
            field=models.CharField(default=apps.lists.models.default_list_id, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
