# Generated by Django 5.2.2 on 2026-03-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_alter_shoppinglist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listmember',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
