# Generated by Django 5.2.2 on 2026-03-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_shoppinglist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='description',
            field=models.TextField(blank=True, db_default=models.Value(''), default=''),
        ),
    ]
