# Generated by Django 5.2.2 on 2026-03-14 15:04

import django.db.models.deletion
import apps.users.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('emoji', models.CharField(max_length=8)),
                ('color_hex', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField(default=1.0)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('checked_at', models.BigIntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.BigIntegerField(default=apps.users.models.now_ms)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_items', to='users.user')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.category')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_items', to='users.user')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lists.shoppinglist')),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='ItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('times_added', models.IntegerField(default=1)),
                ('last_used_at', models.BigIntegerField(default=apps.users.models.now_ms)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.category')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_history', to='lists.shoppinglist')),
            ],
            options={
                'db_table': 'item_history',
                'unique_together': {('list', 'item_name')},
            },
        ),
    ]
