# Generated by Django 5.2.2 on 2026-03-19 02:03

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_seed_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='checked_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.BigIntegerField(default=apps.users.models.now_ms),
        ),
        migrations.AlterField(
            model_name='itemhistory',
            name='last_used_at',
            field=models.BigIntegerField(default=apps.users.models.now_ms),
        ),
    ]
