# Generated by Django 5.2.2 on 2026-03-19 02:06

import apps.items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_checked_at_alter_item_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(default=apps.items.models.default_item_id, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
