# Generated by Django 5.2.2 on 2026-03-19 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_id'),
        ('users', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='added_by',
            field=models.ForeignKey(db_column='added_by', on_delete=django.db.models.deletion.CASCADE, related_name='added_items', to='users.user'),
        ),
        migrations.AlterField(
            model_name='item',
            name='checked_by',
            field=models.ForeignKey(blank=True, db_column='checked_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_items', to='users.user'),
        ),
    ]
