import 'package:drift/drift.dart';

import 'categories.dart';
import 'lists.dart';
import 'users.dart';

/// Table: items
///
/// Represents a single item inside a shopping list.
/// [checkedBy] and [checkedAt] are nullable — they are populated when a
/// member checks the item and cleared when it is unchecked.
@DataClassName('Item')
class Items extends Table {
  /// UUID primary key — generated by the backend before insertion.
  TextColumn get id => text()();

  /// The list this item belongs to. FK → lists.id
  TextColumn get listId => text().references(Lists, #id)();

  /// The user who added this item. FK → users.id
  TextColumn get addedBy => text().references(Users, #id)();

  /// Optional category for grouping. FK → categories.id
  IntColumn get categoryId =>
      integer().nullable().references(Categories, #id)();

  /// Item name. Max 100 characters.
  TextColumn get name => text().withLength(max: 100)();

  /// How much of the item is needed. Stored as REAL (sufficient precision
  /// for shopping quantities; avoids DECIMAL complexity in Drift/Postgres).
  RealColumn get quantity => real().withDefault(const Constant(1.0))();

  /// Unit of measure (e.g. "kg", "L", "pcs"). Nullable — not all items need one.
  TextColumn get unit => text().withLength(max: 20).nullable()();

  /// Optional note or description for the item.
  TextColumn get note => text().nullable()();

  /// Whether the item has been checked off the list.
  BoolColumn get isChecked => boolean()
      .withDefault(const CustomExpression('FALSE'))
      .customConstraint('NOT NULL DEFAULT FALSE')();

  /// The user who checked this item. Nullable — null when unchecked. FK → users.id
  TextColumn get checkedBy => text().nullable().references(Users, #id)();

  /// Timestamp of when the item was checked (UTC). Null when unchecked.
  DateTimeColumn get checkedAt => dateTime().nullable()();

  /// Position in the list. Used for manual reordering (future feature).
  IntColumn get sortOrder => integer().withDefault(const Constant(0))();

  /// Timestamp of creation (UTC).
  DateTimeColumn get createdAt => dateTime()();

  @override
  Set<Column> get primaryKey => {id};
}
