import 'package:backend/database/tables/users.dart';
import 'package:drift/drift.dart';

/// Table: lists
///
/// Represents a shopping list. Each list has a unique 6-character [shareCode]
/// that other users can enter to join the list.
/// [ownerId] references the [Users] who created the list.
@DataClassName('ShoppingList')
class Lists extends Table {
  /// UUID primary key — generated by the backend before insertion.
  TextColumn get id => text()();

  /// Human-readable list name. Max 100 characters.
  TextColumn get name => text().withLength(max: 100)();

  /// 6-character alphanumeric code used to share the list.
  /// Unique across all lists.
  TextColumn get shareCode => text().withLength(min: 6, max: 6)();

  /// The user who created this list.
  TextColumn get ownerId => text().references(Users, #id)();

  /// When true, the list is hidden from the active lists view.
  BoolColumn get isArchived => boolean()
      .withDefault(const CustomExpression('FALSE'))
      .customConstraint('NOT NULL DEFAULT FALSE')();

  /// Timestamp of creation (UTC).
  DateTimeColumn get createdAt => dateTime()();

  /// Timestamp of the last modification (UTC).
  /// Must be updated manually on every write operation.
  DateTimeColumn get updatedAt => dateTime()();

  @override
  Set<Column> get primaryKey => {id};

  /// Enforces uniqueness of [shareCode] at the database level.
  @override
  List<Set<Column>> get uniqueKeys => [
        {shareCode},
      ];
}
