import 'package:drift/drift.dart';

/// Table: users
///
/// Stores anonymous users identified by a device-generated UUID.
/// No traditional authentication — users are distinguished by [id] alone.
@DataClassName('User')
class Users extends Table {
  /// UUID primary key — generated by the backend (uuid package) before insertion.
  TextColumn get id => text()();

  /// Display name shown to other members. Max 50 characters.
  TextColumn get displayName => text().withLength(max: 50)();

  /// Single emoji representing the user's avatar.
  /// Up to 5 chars to accommodate multi-byte emoji sequences.
  TextColumn get avatarEmoji => text().withLength(max: 5)();

  /// FCM device token for push notifications.
  /// Nullable — only set when the user grants notification permission.
  TextColumn get deviceToken => text().nullable()();

  /// Timestamp of when the user was created (UTC).
  DateTimeColumn get createdAt =>
      dateTime().withDefault(currentDateAndTime)();

  @override
  Set<Column> get primaryKey => {id};
}
